#! /usr/bin/python3

##--------------------------------------------------------------------\
#   cryptography_examples
#   './cryptography_examples/src/asymmetric/rsa/decrypt_test.py'
#   Some (mostly) AI generated test cases, for fun.
#
#   WARNING: ciphertext here is generated by actually encrypting known
#   messages with the encrypt class, so it is real (not random strings).
#
#   This file shows the TWO roles of decrypt.py:
#     1. Legitimate decryption with the private key (instant)
#     2. The naive attack: factor n by trial division to recover the key
#
#   Last update: June 02, 2026
##--------------------------------------------------------------------\

import pandas as pd
from encrypt import encrypt
from decrypt import decrypt


print("=== RSA Decrypt Class Example ===")
print("(TEXTBOOK RSA - educational only)")

# Build real test cases by encrypting known messages first.
print("\n=== CREATING TEST CASES ===")

real_test_cases = [
    {'name': 'HELLO (classic 61/53)', 'plaintext': 'HELLO', 'P': 61, 'Q': 53, 'E': 17},
    {'name': 'RSA (larger primes)',  'plaintext': 'RSA',   'P': 10007, 'Q': 10037, 'E': 17},
    {'name': 'KEYS (101/113)',       'plaintext': 'KEYS',  'P': 101, 'Q': 113, 'E': 13},
]

for case in real_test_cases:
    enc_options = pd.DataFrame({
        'P': [case['P']], 'Q': [case['Q']], 'E': [case['E']],
        'OUTPUT_FORMAT': ['INT'], 'SHOW_STEPS': [False]
    })
    encryptor = encrypt(None, enc_options)
    stats = encryptor.get_cipher_stats()
    case['ciphertext'] = encryptor.encrypt_message(case['plaintext'])
    case['n'] = stats['modulus_n']
    case['d'] = stats['secret_d']   # only used for the legitimate-decrypt demo
    print(f"  {case['name']}: '{case['plaintext']}' -> {case['ciphertext']}  (n={case['n']})")

print(f"\n{'='*60}")
print("PART 1: LEGITIMATE DECRYPTION (you hold the private key)")
print('='*60)

for case in real_test_cases:
    print(f"\n--- {case['name']} ---")
    options = pd.DataFrame({
        'N': [case['n']], 'E': [case['E']], 'D': [case['d']],
        'INPUT_FORMAT': ['INT'], 'SHOW_STEPS': [False]
    })
    cipher = decrypt(None, options)
    result = cipher.decrypt_message(case['ciphertext'])
    print(f"  Ciphertext: {case['ciphertext']}")
    print(f"  Decrypted : '{result}'")
    print(f"  Expected  : '{case['plaintext']}'")
    print(f"  Match: {'✓' if result == case['plaintext'] else '✗'}")

print(f"\n{'='*60}")
print("PART 2: THE ATTACK (you only have the PUBLIC key)")
print('='*60)
print("The attacker has (e, n) and the ciphertext, but NOT d.")
print("The only way in is to factor n. Watch the effort scale.\n")

for case in real_test_cases:
    print(f"\n--- Attacking: {case['name']} ---")
    # Attacker is given ONLY n and e (no d)
    attacker = decrypt(None, pd.DataFrame({
        'N': [case['n']], 'E': [case['E']],
        'INPUT_FORMAT': ['INT'], 'SHOW_STEPS': [False]
    }))
    attacker.estimate_attack_cost()
    print()
    result = attacker.brute_force_decrypt(case['ciphertext'])
    print(f"  Attack {'SUCCEEDED' if result == case['plaintext'] else 'did not match'}")

print(f"\n{'='*60}")
print("RSA DECRYPT SUMMARY")
print('='*60)
print("""
RSA DECRYPTION KEY INSIGHTS:

1. ASYMMETRIC, NOT SYMMETRIC:
    - Encrypt with the PUBLIC key, decrypt with the PRIVATE key
    - Unlike RC4/Caesar, the two parties share NO secret in advance

2. THE EASY DIRECTION:
    - With d in hand, m = c^d mod n is instant

3. THE HARD DIRECTION (the attack):
    - Without d, you must FACTOR n into p and q
    - Trial division works here only because our primes are tiny
    - Worst-case effort grows like sqrt(n): every added bit ~doubles it

4. WHY REAL RSA SURVIVES THIS:
    - Real n is 2048+ bits; sqrt(n) is astronomically large
    - No classical computer can trial-divide that in any human timescale

5. WHAT THIS TEACHES ABOUT MODERN CRYPTO:
    - Security can rest on a problem being HARD, not on secrecy of method
    - Key SIZE is a direct, measurable security parameter
    - This is the foundation the whole modern internet leans on
""")
